services:
  mirte-dev:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mirte-dev
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - ./ws:/workspaces/mirte_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
